apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    env: prod
    tier: frontend
  name: my-pod
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - sleep 3600
    env:
    - name: SOME_VARIABLE
      value: some-value
    image: nginx
    name: my-pod
    ports:
    - containerPort: 8080
    resources:
      limits:
        cpu: 200m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}