apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: my-pod
spec:
  containers:
  - image: alpine
    name: my-pod
    command: ["ls", "/etc/foo"]
    volumeMounts:
    - name: secrets-volume
      mountPath: "/etc/foo"
      readOnly: true
  volumes:
  - name: secrets-volume
    secret:
      secretName: my-secret
