apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  securityContext:
    runAsUser: 1000
  containers:
  - image: nginx
    name: my-pod
    securityContext:
      runAsUser: 2000 # container will run as user 2000
      capabilities:
        add:
        - SYS_TIME
        - NET_ADMIN
