apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: my-pod
spec:
  containers:
  - image: alpine
    name: my-pod
    command: ["env"]
    envFrom:
    - configMapRef:
        name: my-configmap

