apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: my-pod
spec:
  containers:
  - image: alpine
    name: my-pod
    command: ["env"]
    env:
    - name: SOME_VALUE
      valueFrom:
        configMapKeyRef:
          name: my-configmap
          key: OTHER_VALUE

